apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ace-minimal-image-build-and-push
spec:
  # The security and environment settings are needed for OpenShift in a non-default
  # namespace such as cp4i. Kaniko is expecting to be root in the container.
  stepTemplate:
    securityContext:
      runAsUser: 0
    env:
      - name: "HOME"
        value: "/tekton/home"
  params:
    - name: dockerRegistry
      type: string
    - name: aceDownloadUrl
      type: string
    - name: url
      type: string
    - name: revision
      type: string
    - name: runtimeImage
      type: string
    - name: aceDockerFile
      type: string
  steps:
    - name: clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.18.1
      script: |
        #!/bin/sh
        cd /work
        git clone "https://github.com/trevor-dolby-at-ibm-com/ace-docker"
        ls -l /work/ace-docker/experimental/ace-minimal
      volumeMounts:
        - mountPath: /work
          name: work
    - name: ace-minimal-push
      image: gcr.io/kaniko-project/executor:v0.16.0
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/work/ace-docker/$(params.aceDockerFile)
        - --destination=$(params.dockerRegistry)/$(params.runtimeImage)
        - --context=/work/ace-docker/experimental/ace-minimal
        - --build-arg=DOWNLOAD_URL=$(params.aceDownloadUrl)
        - --skip-tls-verify
      volumeMounts:
        - mountPath: /work
          name: work
  volumes:
    - name: work
      emptyDir: {}
