apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ace-minimal-image-pipeline-run-
  # Fixed name allows "tkn pr delete ace-minimal-image-pipeline-run-1 -f ; kubectl apply -f tekton/ace-minimal-image-pipeline-run.yaml ; tkn pr logs ace-minimal-image-pipeline-run-1 -f"
  #name: ace-minimal-image-pipeline-run-1
spec:
  serviceAccountName: ace-tekton-service-account
  # Use this instead if building in a CP4i environment 
  # (normally only needed if using Maven)
  #serviceAccountName: cp4i-tekton-service-account
  pipelineRef:
    name: ace-minimal-image-pipeline
  params:
    - name: dockerRegistry
      # OpenShift
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
      #value: "quay.io/trevor_dolby"
      #value: "us.icr.io/ace-containers"
      #value: "aceDemoRegistry.azurecr.io"
      # Minikube
      value: "192.168.49.2:5000/default"
    - name: aceDownloadUrl
      value: "https://iwm.dhe.ibm.com/sdfdl/v2/regs2/mbford/Xa.2/Xb.WJL1CuPI9omKj5inyv9-ir8PMDDUU8v2iYo-Oc5KPVI/Xc.13.0.1.0-ACE-LINUX64-DEVELOPER.tar.gz/Xd./Xf.lPr.D1vk/Xg.12260000/Xi.swg-wmbfd/XY.regsrvs/XZ._4mLAwxEK3xwdP7B6oAhifJgsNyp-ePc/13.0.1.0-ACE-LINUX64-DEVELOPER.tar.gz"
    - name: runtimeImage
      # Tag should match the product version; the image will be pushed to 
      # the dockerRegistry specified above.
      value: "ace-minimal:13.0.1.0-alpine"
