apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-minimal-image-pipeline
spec:
  params:
    - name: dockerRegistry
      type: string
    - name: aceDownloadUrl
      type: string
    - name: url
      type: string
      default: "https://github.com/trevor-dolby-at-ibm-com/ace-demo-pipeline"
    - name: revision
      type: string
      default: "main"
    - name: runtimeImage
      type: string
      default: "ace-minimal:12.0.10.0-alpine"
    - name: aceDockerFile
      type: string
      default: "experimental/ace-minimal/Dockerfile.alpine"
  tasks:
    - name: build-images
      taskRef:
        name: ace-minimal-java11-image-build-and-push
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
        - name: aceDownloadUrl
          value: $(params.aceDownloadUrl)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: runtimeImage
          value: $(params.runtimeImage)
        - name: aceDockerFile
          value: $(params.aceDockerFile)
