apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-minimal-build-image-pipeline
spec:
  params:
    - name: dockerRegistry
      type: string
    - name: aceDownloadUrl
      type: string
    - name: url
      type: string
      default: "https://github.com/ot4i/ace-demo-pipeline"
    - name: revision
      type: string
      default: "main"
    - name: buildImage
      type: string
      default: "ace-minimal-build:13.0.4.0-alpine"
    - name: runtimeImage
      type: string
      default: "ace-minimal:13.0.4.0-alpine"
    - name: aceDockerFile
      type: string
      default: "experimental/ace-minimal/Dockerfile.alpine"
  tasks:
    - name: runtime-image
      taskRef:
        name: ace-minimal-image-build-and-push
      params:
        - name: outputRegistry
          value: $(params.dockerRegistry)
        - name: aceDownloadUrl
          value: $(params.aceDownloadUrl)
        - name: runtimeImage
          value: $(params.runtimeImage)
        - name: aceDockerFile
          value: $(params.aceDockerFile)
    - name: build-image
      taskRef:
        name: ace-minimal-build-image-build-and-push
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: buildImage
          value: $(params.buildImage)
        - name: runtimeImage
          value: $(params.runtimeImage)
      runAfter:
        - runtime-image
