apiVersion: v1
kind: Pod
metadata:
  name: force-pull
spec:
  containers:
  - name: force-pull-base
    imagePullPolicy: Always
    image: us.icr.io/ace-registry/ace-minimal:12.2008.3.0-alpine
    command: ["sleep"]
    args: ["10"]
  - name: force-pull-build
    imagePullPolicy: Always
    image: us.icr.io/ace-registry/ace-minimal-build:12.2008.3.0-alpine
    command: ["sleep"]
    args: ["10"]
  restartPolicy: Never
