apiVersion: v1
kind: ServiceAccount
metadata:
  name: ace-tekton-service-account
imagePullSecrets:
  - name: regcred
  # Needed for cp.icr.io if using the "ace" image 
  #- name: ibm-entitlement-key
secrets:
  - name: regcred
  # Needed for cp.icr.io if using the "ace" image 
  #- name: ibm-entitlement-key
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["services", "deployments", "pods", "pods/exec", "pods/log"]
  verbs: ["get", "create", "update", "patch", "list", "delete", "exec"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: ace-tekton-service-account
