apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tea-tekton-knative
spec:
  template:
    spec:
      volumes:
      - name: secret-volume-2
        secret:
          secretName: jdbc-secret
      imagePullSecrets:
      - name: regcred
      containers:
      - name: tea-tekton-knative
        image: DOCKER_REGISTRY/tea-tekton:latest
        ports:
        - containerPort: 7800
        volumeMounts:
        - name: secret-volume-2
          mountPath: /var/run/secrets/jdbc
