apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cp4i-pipeline
  namespace: cp4i
spec:
  params:
    - name: dockerRegistry
      type: string
    - name: url
      type: string
      default: "https://github.com/ot4i/ace-demo-pipeline"
    - name: revision
      type: string
      default: "main"
    - name: buildImage
      type: string
      default: "ace-minimal-build:12.0.10.0-alpine"
    - name: runtimeImage
      type: string
      default: "ace-server-prod:12.0.11.1-r1"
      #default: "ace-server-prod:12.0.10.0-r1"
  tasks:
    - name: build-from-source
      taskRef:
        name: cp4i-build
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: buildImage
          value: $(params.buildImage)
        - name: runtimeImage
          value: $(params.runtimeImage)
    - name: component-test-in-cp4i
      taskRef:
        name: component-test-in-cp4i
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: tag
          value: "$(tasks.build-from-source.results.tag)"
        - name: ctsha
          value: "$(tasks.build-from-source.results.ctsha)"
      runAfter:
        - build-from-source
    - name: deploy-to-cp4i
      taskRef:
        name: deploy-to-cp4i
      params:
        - name: dockerRegistry
          value: $(params.dockerRegistry)
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: tag
          value: "$(tasks.build-from-source.results.tag)"
        - name: sha
          value: "$(tasks.build-from-source.results.sha)"
      runAfter:
        - component-test-in-cp4i
