apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cp4i-pipeline-run-
  namespace: cp4i
spec:
  serviceAccountName: cp4i-tekton-service-account
  pipelineRef:
    name: cp4i-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default"
      # Minikube
      #value: "192.168.49.2:5000/default"
    - name: appName
      value: "tea-tekton-cp4i"
    - name: url
      value: "https://github.com/mrislam11378/ace-demo-pipeline.git"
    - name: revision
      value: "main"
    - name: buildImage
      value: "cp.icr.io/cp/appc/ace:12.0.12.0-r1"
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-minimal-build:12.0.1w.0-alpine"
    - name: runtimeBaseImage
      value: "cp.icr.io/cp/appc/ace-server-prod:12.0.12.0-r1-20240417-022324"
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/default/ace-server-prod:12.0.12.0-r1-20240417-022324"
