apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cp4i-pipeline-run-
  namespace: cp4i
spec:
  serviceAccountName: cp4i-tekton-service-account
  pipelineRef:
    name: cp4i-pipeline
  params:
    - name: dockerRegistry
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000"
      # Minikube
      #value: "192.168.49.2:5000/default"
    - name: appName
      value: "tea-tekton-cp4i"
    - name: url
      value: "https://github.com/trevor-dolby-at-ibm-com/ace-demo-pipeline"
    - name: revision
      value: "main"
    - name: buildImage
      value: "cp.icr.io/cp/appc/ace:13.0.1.0-r1"
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/cp4i/ace-minimal-build:13.0.1.0-alpine"
    - name: runtimeBaseImage
      value: "cp.icr.io/cp/appc/ace-server-prod:13.0.1.0-r2-20241024-142903"
      #value: "image-registry.openshift-image-registry.svc.cluster.local:5000/cp4i/ace-server-prod:13.0.1.0-r2-20241024-142903"
