apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  annotations:
    appconnect.ibm.com/hibernate: 'false'
  name: APP_NAME
  namespace: APP_NAMESPACE
spec:
  flowType:
    toolkitFlow: true
  license:
    accept: true
    license: L-KPRV-AUG9NC
    use: AppConnectEnterpriseNonProductionFREE
  template:
    spec:
      containers:
        - image: >-
            IR_IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          name: runtime
          resources:
            requests:
              cpu: 300m
              memory: 368Mi
      # This is now handled via the "default" service account
      # kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "regcred"}]}'
      #imagePullSecrets:
      #- name: regcred
  configurations:
    - teajdbc-policy
    - default-policy
    - teajdbc
  version: 13.0.1.0-r2
