apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  annotations:
    appconnect.ibm.com/hibernate: 'false'
  name: tea-tekton-cp4i-ct
  namespace: cp4i
spec:
  flowType:
    toolkitFlow: true
  license:
    accept: true
    license: L-QECF-MBXVLU
    use: AppConnectEnterpriseNonProductionFREE
  configurations:
    - teajdbc-policy
    - default-policy
    - teajdbc
  template:
    spec:
      containers:
        - image: >-
            DOCKER_REGISTRY/tea-tekton-cp4i-ct:IMAGE_TAG
          env:  
            - name: MQSI_PREVENT_CONTAINER_SHUTDOWN
              value: 'true'
          imagePullPolicy: Always
          name: runtime
          livenessProbe:
            failureThreshold: 1000000
          resources:
            # Run tests more quickly
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 2000m
              memory: 1024Mi
      imagePullSecrets:
        - name: regcred
  version: 12.0.12.0-r2
